[package]
name = "pumpkin_smash_game"
version = "0.1.0"
authors = ["HRVST Oracle <hrvstoracle@proton.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde = "1.0"
serde_json = "1.0"
rand = "0.8"
web-sys = "0.3"
